"""
Report generation in multiple formats
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict

class ReportGenerator:
    """Generates vulnerability reports in various formats"""
    
    def __init__(self, scan_results: Dict):
        self.results = scan_results
        self.severity_colors = {
            'critical': '#FF0000',
            'high': '#FF6600',
            'medium': '#FFCC00',
            'low': '#00CC00',
            'info': '#0099FF'
        }
    
    def generate(self, output_file: str, format_type: str = 'html'):
        """Generate report in specified format"""
        if format_type == 'html':
            self.generate_html(output_file)
        elif format_type == 'json':
            self.generate_json(output_file)
        elif format_type == 'text':
            self.generate_text(output_file)
    
    def generate_html(self, output_file: str):
        """Generate HTML report"""
        html_template = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Cryptographic Vulnerability Scan Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f0f0f0; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; margin-bottom: 20px; }}
        .summary {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin: 20px 0; }}
        .summary-card {{ padding: 20px; border-radius: 8px; text-align: center; color: white; }}
        .critical {{ background: #dc3545; }}
        .high {{ background: #fd7e14; }}
        .medium {{ background: #ffc107; color: black; }}
        .low {{ background: #28a745; }}
        .finding {{ background: white; border-left: 4px solid #007bff; padding: 15px; margin: 10px 0; border-radius: 4px; }}
        .vulnerability {{ border-left-color: #dc3545; }}
        .recommendation {{ background: #d4edda; padding: 10px; border-radius: 4px; margin-top: 10px; }}
        .compliance {{ margin: 20px 0; padding: 15px; background: #f8f9fa; border-radius: 8px; }}
        .pass {{ color: #28a745; }}
        .fail {{ color: #dc3545; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #f8f9fa; }}
        .file-path {{ color: #6c757d; font-size: 0.9em; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔒 Cryptographic Vulnerability Scan Report</h1>
            <p>Scan Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p>Target: {self.results.get('target', self.results.get('repo_url', 'Unknown'))}</p>
            <p>Files Scanned: {self.results['total_files']}</p>
        </div>
        
        <div class="summary">
            <div class="summary-card critical">
                <h2>{self.results['critical']}</h2>
                <p>Critical</p>
            </div>
            <div class="summary-card high">
                <h2>{self.results['high']}</h2>
                <p>High</p>
            </div>
            <div class="summary-card medium">
                <h2>{self.results['medium']}</h2>
                <p>Medium</p>
            </div>
            <div class="summary-card low">
                <h2>{self.results['low']}</h2>
                <p>Low</p>
            </div>
        </div>
        
        <h2>📊 Detailed Findings ({self.results['total_findings']} total)</h2>
        <table>
            <thead>
                <tr>
                    <th>Severity</th>
                    <th>File</th>
                    <th>Line</th>
                    <th>Type</th>
                    <th>Details</th>
                    <th>Recommendation</th>
                </tr>
            </thead>
            <tbody>
                {self._generate_finding_rows()}
            </tbody>
        </table>
        
        <h2>📋 Compliance Check</h2>
        {self._generate_compliance_section()}
        
        <h2>💡 Recommendations Summary</h2>
        <ul>
            <li>Replace all deprecated algorithms (MD5, SHA1, DES, RC4) with modern alternatives</li>
            <li>Use key management systems instead of hardcoded keys</li>
            <li>Implement proper encryption modes (avoid ECB)</li>
            <li>Use cryptographically secure random number generators</li>
            <li>Keep all cryptographic libraries up to date</li>
        </ul>
        
        <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #6c757d;">
            <p>Generated by Crypto Vulnerability Scanner</p>
        </footer>
    </div>
</body>
</html>
        """
        
        with open(output_file, 'w') as f:
            f.write(html_template)
    
    def _generate_finding_rows(self) -> str:
        """Generate HTML rows for findings"""
        rows = []
        for finding in self.results.get('vulnerabilities', self.results.get('findings', [])):
            severity = finding.get('severity', 'info')
            color = self.severity_colors.get(severity, '#999')
            rows.append(f"""
                <tr>
                    <td style="color: {color}; font-weight: bold;">{severity.upper()}</td>
                    <td class="file-path">{finding.get('file', 'Unknown')}</td>
                    <td>{finding.get('line', 'N/A')}</td>
                    <td>{finding.get('type', finding.get('algorithm', 'Unknown'))}</td>
                    <td>{finding.get('message', '')}</td>
                    <td class="recommendation">{finding.get('recommendation', 'Review manually')}</td>
                </tr>
            """)
        return ''.join(rows)
    
    def _generate_compliance_section(self) -> str:
        """Generate compliance section HTML"""
        compliance = self.results.get('compliance', {})
        html = ""
        
        for standard, results in compliance.items():
            status = "✅ PASS" if results.get('compliant', False) else "❌ FAIL"
            css_class = "pass" if results.get('compliant', False) else "fail"
            html += f"""
            <div class="compliance">
                <h3>{standard}: <span class="{css_class}">{status}</span></h3>
                <p>{results.get('message', '')}</p>
                <p>Issues found: {len(results.get('issues', []))}</p>
            </div>
            """
        
        return html
    
    def generate_json(self, output_file: str):
        """Generate JSON report"""
        report = {
            'scan_metadata': {
                'date': datetime.now().isoformat(),
                'target': self.results.get('target', self.results.get('repo_url')),
                'total_files': self.results['total_files'],
                'total_findings': self.results['total_findings']
            },
            'summary': {
                'critical': self.results['critical'],
                'high': self.results['high'],
                'medium': self.results['medium'],
                'low': self.results['low']
            },
            'findings': self.results['vulnerabilities'],
            'compliance': self.results['compliance']
        }
        
        with open(output_file, 'w') as f:
            json.dump(report, f, indent=2)
    
    def generate_text(self, output_file: str):
        """Generate plain text report"""
        with open(output_file, 'w') as f:
            f.write("CRYPTOGRAPHIC VULNERABILITY SCAN REPORT\n")
            f.write("="*50 + "\n\n")
            f.write(f"Scan Date: {datetime.now()}\n")
            f.write(f"Target: {self.results.get('target', self.results.get('repo_url'))}\n")
            f.write(f"Files Scanned: {self.results['total_files']}\n\n")
            
            f.write("SUMMARY\n")
            f.write("-"*20 + "\n")
            f.write(f"Critical: {self.results['critical']}\n")
            f.write(f"High: {self.results['high']}\n")
            f.write(f"Medium: {self.results['medium']}\n")
            f.write(f"Low: {self.results['low']}\n\n")
            
            f.write("DETAILED FINDINGS\n")
            f.write("-"*20 + "\n")
            for finding in self.results['vulnerabilities']:
                f.write(f"[{finding.get('severity', 'info').upper()}] ")
                f.write(f"{finding.get('file', 'Unknown')}:{finding.get('line', 'N/A')}\n")
                f.write(f"  {finding.get('message', '')}\n")
                if 'recommendation' in finding:
                    f.write(f"  Fix: {finding['recommendation']}\n")
                f.write("\n")